### ISSUE TITLE
عدم دسترسی به وب سرویس step1

### ISSUE THREAD

**Issue by sEhsanTaher** [sehsanm/sbunlpcourse#2]
<p dir='rtl' align='right'>
سلام
</p>
<p dir='rtl' align='right'>
wsdl  ابزار step-1 رو نمیشه خارج از آزمایشگاه استفاده کرد؟
<br/>
آدرس 192.168.40.40(آدرس wsdl) قابل رویت نیست(طبیعتاً داخل شبکه دانشگاه)
<br/><br/>
ممنون میشم راهی معرفی کنید که بشه از step1 توی کدمون استفاده کنیم.
</p>

**Comment by kibamin** [comment]
منم همین مشکل دارم
داخل وب سرویس با آدرس زیر که میرم 
http://step1.nlp.sbu.ac.ir/services/Service.asmx?op=Tokenize
 و وارد آدرس زیر میشود چون لوکال جواب نمیگیرم
http://192.168.40.40/services/Service.asmx/Tokenize

آیا راه دیگه ای هست که بشه از step1 استفاده کرد؟؟

**Comment by sehsanm** [comment]
ظاهرا وب سرویس استپ وان فقط از داخل شبکه دانشگاه در دسترس هست.  و علی الظاهر سرویس  چند روز گذشته دچار اختلال شده که یکی از بچه های آزمایشگاه در حال بر طرف کردن مشکل هست.  اگر  خبری از رفع شدن مشکل شد من اینجا به شما اطلاع میدم

**Comment by kibamin** [comment]
الان ما فعلا فقط فایل تست آپلود کنیم؟
نیاز به کد نیست؟

**Comment by sehsanm** [comment]
بله مرحله اول فایل های تست 
دوم فایل خروجی 
سوم  فایل مرجع 
چهارم کد

**Comment by sehsanm** [comment]
وب سرویس دوباره به زندگی بازگشته !
[STEP-1](http://step1.nlp.sbu.ac.ir/services/Service.asmx)

**Comment by sEhsanTaher** [comment]
<p dir="rtl">
باتشکر 🙏🏻🙏🏻🙏🏻
</p>
