### ISSUE TITLE
Tabs number

### ISSUE THREAD

**Issue by nazilaMokhtari** [sehsanm/sbunlpcourse#31]
u wrote that "Except for end of sentence each line must have 6 tabs characters (\t)", but cause we have only 6 columns, so there are 5 tabs, am I right? or we have to add another tab in the end of each line?

**Comment by sehsanm** [comment]
You are right  5 tabs is correct.  Having said that, adding more columns will not break the scoring script. It will ignore the additional columns.

**Comment by sehsanm** [comment]
Thanks for raising this, I updated the Readme file
