### ISSUE TITLE
index of token in sentence or file ? 

### ISSUE THREAD

**Issue by abb4s** [sehsanm/sbunlpcourse#33]
I'm not sure but I think you mean "index of the token in the total string of input file" by "Index of the token in the sentence. Starting from 0". and indexes are the count of characters from the start of the string until that token. am I right?
it would be more understandable if you give a sample input and output file.

**Comment by sehsanm** [comment]
Hi 
the index is  from start of sentece to the end of it. 
please have a look at /data/sample folder in repository
